### ISSUE TITLE
Edit this page button on book page goes to nonexistent page

### ISSUE THREAD

**Issue by byandell** [hadley/adv-r#922] opened 2017-11-20 16:48 UTC
Hadley,
If you go to
http://adv-r.had.co.nz/Environments.html
and click the Edit this page button, you are sent to
https://github.com/hadley/adv-r/edit/master/Environments.rmd
which does not exist (error 404). Contributors should instead be sent (I think) to
https://github.com/hadley/adv-r/blob/master/book/tex/Environments.tex
where they can do a pull request.
Brian

**Comment by hadley** [comment] 2017-11-20 16:51
Duplicate of #798

**Closed by hadley** 2017-11-20 16:51 UTC
