### ISSUE TITLE
Missing figure

### ISSUE THREAD

**Issue by theosanderson** [hadley/adv-r#1038] opened 2018-05-01 13:07 UTC
The sine curve graph on http://adv-r.had.co.nz/Computing-on-the-language.html appears to reference a temporary URL that doesn't exist.

**Comment by jdnewmil** [comment] 2018-06-30 20:08
This seems to be a systematic problem with all plot output throughout the website.

**Comment by hadley** [comment] 2018-07-06 12:58
Duplicate of #816; you want the second edition: http://adv-r.hadley.nz/

**Closed by hadley** 2018-07-06 12:58 UTC
