### ISSUE TITLE
More relevant lazy evaluation example in functions chapter (for R 3.2.0 and higher)

### ISSUE THREAD

**Issue by gumeo** [hadley/adv-r#708] opened 2015-10-22 09:45 UTC
The lazy evaluation example in the functions chapter is no longer working (see [#672](https://github.com/hadley/adv-r/issues/672)). 

I propose an alternative example:

```
add <- function(x) {
  function(y) x + y
}

adders <- list()

for(i in 1:10) {
  adders[[i]] <- add(i)
}
adders[[1]](10)
adders[[10]](10)

add <- function(x) {
  force(x)
  function(y) x + y
}

adders2 <- list()

for(i in 1:10) {
  adders2[[i]] <- add(i)
}
adders2[[1]] (10)
adders2[[10]] (10)
```

This demonstrates the desired difference when using force. 

It is mentioned in the book that this applies to loops, so since of R 3.2.0 this no longer applies to higher order functions:

> Higher order functions such as the apply functions and Reduce() now force arguments to the functions they apply in order to eliminate undesirable interactions between lazy evaluation and variable capture in closures. 

"I assign the copyright of this contribution to Hadley Wickham".

**Comment by gumeo** [comment] 2015-10-27 10:03
This issue also occurs in the Laziness subsection of [Behavioural FOs](http://adv-r.had.co.nz/Function-operators.html#behavioural-fos). 

It might not be clear to the reader why there is no difference in the output. Maybe a message explaining the update might be relevant. I do not feel that the use of loops is adequate, since the topic is on functionals and function operators.

**Comment by hadley** [comment] 2017-01-23 20:50
Duplicate of #740

**Closed by hadley** 2017-01-23 20:50 UTC
