### ISSUE TITLE
Missing figure on memory page

### ISSUE THREAD

**Issue by dlebauer** [hadley/adv-r#812] opened 2017-04-21 04:19 UTC
In http://adv-r.had.co.nz/memory.html

The plot generated by 

```r
sizes <- sapply(0:50, function(n) object_size(seq_len(n)))
plot(0:50, sizes, xlab = "Length", ylab = "Size (bytes)", 
  type = "s")
```

is missing, as seen in this screenshot

<img width="279" alt="screen shot 2017-04-20 at 11 17 44 pm" src="https://cloud.githubusercontent.com/assets/464871/25262726/b5c613f6-261f-11e7-8939-5d7d6e7260af.png">

**Comment by justbennet** [comment] 2018-02-06 13:51
This is a duplicate of Issue #816

**Closed** 2018-02-06 18:08 UTC
