### ISSUE TITLE
chapter 2: appears to have unnecessary sidebar

### ISSUE THREAD

**Issue by EmilHvitfeldt** [hadley/adv-r#1710] opened 2021-11-26 19:08 UTC
https://github.com/hadley/adv-r/blob/dc49c3872c3530ac08716fd4f4c235b01266a4ce/Names-values.Rmd#L164-L166
<img width="1506" alt="Screen Shot 2021-11-26 at 11 06 34 AM" src="https://user-images.githubusercontent.com/14034784/143622287-47dc7627-839c-450c-9893-d34fd11d5caf.png">

**Comment by hadley** [comment] 2023-03-19 18:08
Duplicate of #1651

**Closed by hadley** 2023-03-19 18:08 UTC
