### ISSUE TITLE
Edit this page link points to non-existent .rmd instead of .Rmd source (and it matters)

### ISSUE THREAD

**Issue by dlebauer** [hadley/adv-r#813] opened 2017-04-21 04:23 UTC
The 'Edit This Page' button on the memory page http://adv-r.had.co.nz/memory.html points to [https://github.com/hadley/adv-r/edit/master/memory.**r**md](https://github.com/hadley/adv-r/edit/master/memory.rmd) which returns the GitHub 404 page but it should really be pointing to  [https://github.com/hadley/adv-r/edit/master/memory.**R**md](https://github.com/hadley/adv-r/edit/master/memory.Rmd)

**Comment by dlebauer** [comment] 2017-04-21 04:24
Also occurs for 100% of a random sample of 3 additional pages

**Comment by fangly** [comment] 2017-06-19 08:30
I observed  this also for the contribute and environments chapters.

**Comment by hadley** [comment] 2017-07-04 14:01
Duplicate of #798

**Closed by hadley** 2017-07-04 14:01 UTC
