### ISSUE TITLE
Broken images in online book.

### ISSUE THREAD

**Issue by jcrodriguez1989** [hadley/adv-r#1469] opened 2019-02-18 14:31 UTC
Images hosted in http://adv-r.had.co.nz/temp_files/figure-html/ not being showed in the online book.

Sections:
[Memory](http://adv-r.had.co.nz/memory.html)
http://adv-r.had.co.nz/temp_files/figure-html/size-q-1.png
http://adv-r.had.co.nz/temp_files/figure-html/size-a-1.png

[Functionals](http://adv-r.had.co.nz/Functionals.html)
http://adv-r.had.co.nz/temp_files/figure-html/roll-mean-1.png
http://adv-r.had.co.nz/temp_files/figure-html/outliers-1.png
http://adv-r.had.co.nz/temp_files/figure-html/roll-apply-1.png

[Function Operators](http://adv-r.had.co.nz/Function-operators.html)
http://adv-r.had.co.nz/Function-operators.html
http://adv-r.had.co.nz/temp_files/figure-html/uniroot-explore-1.png
http://adv-r.had.co.nz/temp_files/figure-html/uniroot-explore-2.png

[Computing on the Language](http://adv-r.had.co.nz/Computing-on-the-language.html)
http://adv-r.had.co.nz/Computing-on-the-language.html
http://adv-r.had.co.nz/temp_files/figure-html/plot-labels-1.png

[Expressions](http://adv-r.had.co.nz/Expressions.html)
http://adv-r.had.co.nz/temp_files/figure-html/curve-demo-1.png

**Comment by hadley** [comment] 2019-02-18 16:41
Duplicate of #798

**Closed by hadley** 2019-02-18 16:41 UTC
