### ISSUE TITLE
Lazy evaluation example no longer works

### ISSUE THREAD

**Issue by csgillespie** [hadley/adv-r#672] opened 2015-04-28 09:24 UTC
The code (http://adv-r.had.co.nz/Functions.html lazy evaluation)

``` r
> add <- function(x) {
+   function(y) x + y
+ }
```

is used to illustrate the issues with lazy evaluation. However, running the code, doesn't reproduce the output in the book

``` r
R> adders <- lapply(1:10, add)
R> adders[[1]](10)
[1] 11
R> adders[[10]](10)
[1] 20
```

``` r
R> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] colorout_1.1-0

loaded via a namespace (and not attached):
[1] tools_3.2.0    fortunes_1.5-2
```

**Comment by hadley** [comment] 2015-04-28 12:14
Yes, this is a change in R 3.2

**Comment by csgillespie** [comment] 2015-04-28 12:18
I guessed that. I suppose I should have asked, do you want "error" reports that are due to R/package  changes.

**Comment by jefferys** [comment] 2015-07-12 20:12
This confused me too, until I found an associated [stack-exchage comment](http://stackoverflow.com/questions/16129902/explain-a-lazy-evaluation-quirk).

**Comment by hadley** [comment] 2017-01-23 20:51
Duplicate of #740

**Closed by hadley** 2017-01-23 20:51 UTC
